<?xml version="1.0"?>
<robot name="base" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="base_thickness" value="0.25" />
  <xacro:property name="base_diam" value="0.7" />
  <xacro:property name="base_mass" value="56.29" />

  <xacro:macro name="base" params="mesh_file">
    <link name="base_footprint">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.001 0.001 0.001" />
        </geometry>
      </visual>
    </link>

    <link name="base_link">
      <visual>
        <geometry>
          <mesh filename="${base_mesh_file}" scale="1.0 1.0 1.0"/>
        </geometry>
        <material name="blue"/>
        <origin xyz="-0.025 0 0.025" rpy= "0 0 0"/>
      </visual>
      <inertial>
        <mass value="${base_mass}"/>
        <!-- inertia tensor taken from CAD file -->
        <inertia ixx="1.27627" ixy="0.000255157" ixz="-0.0693358"
                 iyy="1.78047" iyz="0.000140996"
                 izz="2.28396" />
        <origin xyz="0.035 0 -0.008" rpy= "0 0 0"/>
      </inertial>
      <collision>
        <geometry>
          <cylinder length="${base_thickness}" radius="${base_diam/2}"/>
          <origin xyz="-0.25 0 0.5" rpy= "0 0 0"/>
        </geometry>
      </collision>
    </link>

    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 0.15" rpy="0 0 0" />
      <parent link="base_footprint"/>
      <child link="base_link" />
    </joint>
  </xacro:macro>

</robot>
