<?xml version="1.0"?>
<robot name="passive_wheel" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="passive_wheel_diam" value="0.1" />
  <xacro:property name="passive_wheel_mass" value="0.2" />

  <xacro:macro name="passive_wheel" params="parent *origin">

    <link name="passive_wheel">
      <visual>
        <geometry>
          <sphere radius="${passive_wheel_diam/2}"/>
        </geometry>
      </visual>
      <inertial>
        <mass value="${passive_wheel_mass}"/>
        <inertia ixx="${(2/5)*(passive_wheel_mass*(passive_wheel_diam/2)*(passive_wheel_diam/2))}"
                ixy="0.0" ixz="0.0"
                iyy="${(2/5)*(passive_wheel_mass*(passive_wheel_diam/2)*(passive_wheel_diam/2))}"
                iyz="0.0" izz="${(2/5)*(passive_wheel_mass*(passive_wheel_diam/2)*(passive_wheel_diam/2))}"/>
      </inertial>
      <collision>
        <geometry>
          <sphere radius="${passive_wheel_diam/2}"/>
        </geometry>
      </collision>
    </link>

    <joint name="base_to_passive_wheel" type="fixed">
      <parent link="${parent}"/>
      <child link="passive_wheel"/>
      <xacro:insert_block name="origin" />
    </joint>

    <gazebo reference="passive_wheel">
      <mu1 value="0.0"/>
      <mu2 value="0.0"/>
      <kp value="10000000.0" />
      <kd value="1.0" />
      <material>Gazebo/Grey</material>
    </gazebo>

  </xacro:macro>

</robot>   
